# Generated by Django 4.1 on 2022-09-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('red', models.IntegerField()),
                ('yellow', models.IntegerField()),
                ('white', models.IntegerField()),
                ('orange', models.IntegerField()),
                ('violet', models.IntegerField()),
                ('green', models.IntegerField()),
                ('pink', models.IntegerField()),
            ],
        ),
    ]
